CREATE TABLE IF NOT EXISTS audit_requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  request_id VARCHAR(96) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  request_event_at DATETIME(6) NULL,
  usage_event_at DATETIME(6) NULL,
  user_id BIGINT NULL,
  username VARCHAR(128) NOT NULL DEFAULT '',
  token_id BIGINT NULL,
  token_name VARCHAR(255) NOT NULL DEFAULT '',
  model_name VARCHAR(255) NOT NULL DEFAULT '',
  request_path VARCHAR(255) NOT NULL DEFAULT '',
  relay_format VARCHAR(64) NOT NULL DEFAULT '',
  is_stream BOOLEAN NOT NULL DEFAULT FALSE,
  prompt_hash VARCHAR(64) NOT NULL DEFAULT '',
  prompt_preview TEXT NOT NULL,
  prompt_ciphertext LONGBLOB NULL,
  prompt_nonce VARBINARY(32) NULL,
  prompt_len INT NOT NULL DEFAULT 0,
  prompt_collected BOOLEAN NOT NULL DEFAULT FALSE,
  prompt_tokens INT NOT NULL DEFAULT 0,
  completion_tokens INT NOT NULL DEFAULT 0,
  quota INT NOT NULL DEFAULT 0,
  channel_id BIGINT NULL,
  group_name VARCHAR(128) NOT NULL DEFAULT '',
  use_time_seconds INT NOT NULL DEFAULT 0,
  upstream_request_id VARCHAR(128) NOT NULL DEFAULT '',
  usage_collected BOOLEAN NOT NULL DEFAULT FALSE,
  relation_status VARCHAR(32) NOT NULL DEFAULT 'pending_usage',
  UNIQUE KEY uq_audit_requests_request_id (request_id),
  KEY idx_audit_requests_created_at (created_at),
  KEY idx_audit_requests_user_id (user_id),
  KEY idx_audit_requests_token_id (token_id),
  KEY idx_audit_requests_token_name (token_name),
  KEY idx_audit_requests_model_name (model_name),
  KEY idx_audit_requests_prompt_hash (prompt_hash),
  KEY idx_audit_requests_relation_status (relation_status),
  KEY idx_audit_requests_upstream_request_id (upstream_request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_classifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  request_id VARCHAR(96) NOT NULL,
  category VARCHAR(64) NOT NULL,
  work_verdict VARCHAR(32) NOT NULL,
  confidence DOUBLE NOT NULL DEFAULT 0,
  reason TEXT NOT NULL,
  evidence TEXT NOT NULL,
  classifier_type VARCHAR(32) NOT NULL DEFAULT 'rules',
  classifier_version VARCHAR(64) NOT NULL DEFAULT '',
  review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  review_note TEXT NOT NULL,
  reviewed_by VARCHAR(128) NOT NULL DEFAULT '',
  reviewed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_audit_classifications_request_id (request_id),
  KEY idx_audit_classifications_category (category),
  KEY idx_audit_classifications_work_verdict (work_verdict),
  KEY idx_audit_classifications_review_status (review_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_events_deadletter (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_type VARCHAR(64) NOT NULL DEFAULT '',
  request_id VARCHAR(96) NOT NULL DEFAULT '',
  reason TEXT NOT NULL,
  payload MEDIUMTEXT NOT NULL,
  created_at DATETIME(6) NOT NULL,
  KEY idx_audit_deadletter_event_type (event_type),
  KEY idx_audit_deadletter_request_id (request_id),
  KEY idx_audit_deadletter_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

